package net.dungeonrealms.game.item;

public enum ItemUsage {
	
	LEFT_CLICK_AIR,
	LEFT_CLICK_BLOCK,
	LEFT_CLICK_ENTITY,
	
	RIGHT_CLICK_AIR,
	RIGHT_CLICK_BLOCK,
	RIGHT_CLICK_ENTITY,
	
	INVENTORY_SWAP_PICKUP,
	INVENTORY_SWAP_PLACE,
	INVENTORY_PLACE_ITEM,
	INVENTORY_PICKUP_ITEM,
	
	CONSUME_ITEM,
	
	NONE; //Placeholder
}
